version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: turnos_db_dev
    environment:
      POSTGRES_USER: turnos_user
      POSTGRES_PASSWORD: turnos_password
      POSTGRES_DB: turnos_db
    ports:
      - "5432:5432" # Puerto expuesto al host para poder debugear con DBeaver/PgAdmin
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U turnos_user -d turnos_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile.dev
    container_name: turnos_backend_dev
    ports:
      - "3000:3000"
    volumes:
      - ../apps/backend:/app
      - /app/node_modules # Evita sobreescribir los módulos de Node dentro del contenedor con los del host
    environment:
      - DATABASE_URL=postgresql://turnos_user:turnos_password@db:5432/turnos_db
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ../apps/frontend
      dockerfile: Dockerfile.dev
      args:
        - VITE_API_URL=http://localhost:3000/api
    container_name: turnos_frontend_dev
    ports:
      - "5173:5173"
    volumes:
      - ../apps/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

volumes:
  pgdata_dev:
